name: Deploy Site
on:
  - push
  - workflow_dispatch
jobs:
  update-infrastructure:
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: compile in docker
        run: |
          cd client
          docker build -t build-site .
          docker run \
            --rm \
            -v $(pwd):/app \
            -v /var/www/html:/app/build \
            build-site
