version: "3.8"
services:
  editor:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16-bullseye
    volumes:
      - ../:/app
      - ./.bashrc:/home/node/.bashrc
    working_dir: /app
    command: tail -f /dev/null

  reverse_proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  client:
    image: node:15-alpine
    volumes:
      - ../:/app
    working_dir: /app
    entrypoint: sh
    command: |
      -c "
        cd client
        npm install
        npm start
      "

  pages:
    image: nginx:alpine
    volumes:
      - ./pages.conf:/etc/nginx/conf.d/default.conf
      - ../pages:/usr/share/nginx/html
