services:
  editor:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/app
      - home_cache:/home/node
      - ~/.ssh:/home/developer/.ssh:ro
    environment:
      - DATABASE_URL=postgres://siteuser:postgresewvraer@db:5432/my_db
    env_file:
      - .env
    command: |
      bash -c '
        tail -f /dev/null
      '
  reverse_proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  client:
    image: node:15-alpine
    volumes:
      - ../:/app
    working_dir: /app
    entrypoint: sh
    command: |
      -c "
        cd client
        npm install
        npm start
      "
  app:
    image: node:20-alpine
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 3001:3000
    entrypoint: sh
    command: |
      -c "
        cd app
        npm install
        npm run dev
      "
  db:
    image: timescale/timescaledb-ha:pg17 # pgvector and pgvectorscale pre-installed
    environment:
      - POSTGRES_USER=siteuser
      - POSTGRES_PASSWORD=postgresewvraer
      - POSTGRES_DB=my_db
    volumes:
      - db_data:/var/lib/postgresql/data

  pages:
    image: nginx:alpine
    volumes:
      - ./pages.conf:/etc/nginx/conf.d/default.conf
      - ../pages:/usr/share/nginx/html

volumes:
  db_data:
  home_cache: