version: "3.8"
services:
  editor:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-16-bullseye
    volumes:
    - ../:/app
    - ./.bashrc:/home/node/.bashrc
    working_dir: /app
    command: tail -f /dev/null

  reverse_proxy:
    image: nginx
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80

  container:
    image: node:15-alpine
    volumes:
    - ../:/app
    working_dir: /app
    entrypoint: sh
    command: |
      -c "
        cd container
        npm install
        npm start
      "

  blog:
    image: node:15-alpine
    volumes:
    - ../:/app
    working_dir: /app
    entrypoint: sh
    command: |
      -c "
        cd blog
        npm install
        npm start
      "

  navbar:
    image: node:15-alpine
    volumes:
    - ../:/app
    working_dir: /app
    entrypoint: sh
    command: |
      -c "
        cd navbar
        npm install
        npm start
      "
  pages:
    image: nginx:alpine
    volumes:
    - ../pages:/usr/share/nginx/html