import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { filesystemService } from "@/services/filesystemService";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const files = await filesystemService.listFilesInDirectory("../pages");
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen m-0 p-0 `}>
        <div className="flex flex-row w-full overflow-hidden">
          <div className="min-w-80 w-80 border rounded m-3">
            sidebar
            <hr />
            <div className="p-5">
              {files.map((f) => (
                <div key={f}>
                  <Link className="m-3 hover:bg-sky-700" href={`/blog/${f}`}>
                    {f}
                  </Link>
                </div>
              ))}
            </div>
          </div>
          <div className="flex-1 text-wrap">{children}</div>
        </div>
      </body>
    </html>
  );
}
