name: Deploy Site
on:
  - push
  - workflow_dispatch
jobs:
  update-infrastructure:
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: compile in docker
        run: |
          docker pull ghcr.io/linuxserver/swag
          docker pull node:15-alpine
          docker build -t personal-site client/

          cd deployment
          docker-compose build
          docker-compose down
          docker-compose up -d
